name: VoltAsist
options:
  bundleIdPrefix: com.ersensen
  projectFormat: 55
targets:
  VoltAsist:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
    settings:
      base:
        DEVELOPMENT_TEAM: 9DM9S4CD3U
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen: {}
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait"
        PRODUCT_BUNDLE_IDENTIFIER: com.ersensen.voltasist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        OTHER_SWIFT_FLAGS: ""
      configs:
        debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.ersensen.voltasist
        release:
          PRODUCT_BUNDLE_IDENTIFIER: com.ersensen.voltasist
    dependencies:
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseAnalytics
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Firebase
        product: FirebaseStorage
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 11.0.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS.git
    from: 7.0.0
